version: '3.7'

services:
  mysql:
    container_name: mysql2
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3307:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /home/lkit/tmp/mysql:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf

